# What is Numpy?

### NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.
##### Create an Array
##### Built in Methods
##### Indexing and Slicing
##### Broadcasting
##### Selection
##### More Built in functions

##### Import the Library

In [4]:
import numpy as np

##### Creating an Array

In [5]:
my_list = [1,2,3,4]

In [6]:
np.array(my_list)

array([1, 2, 3, 4])

In [7]:
matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [9]:
np.array(matrix)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Built in Methods

In [10]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(2)

array([0.20497072, 0.2837008 ])

In [20]:
np.random.rand(2)

array([0.79974518, 0.38773471])

In [21]:
np.random.rand(4,4)

array([[0.74007608, 0.97837237, 0.96738607, 0.84309694],
       [0.53436157, 0.35601714, 0.55071907, 0.44781574],
       [0.34052252, 0.63064526, 0.31849273, 0.76757285],
       [0.77073819, 0.53299665, 0.30441437, 0.341616  ]])

In [22]:
np.random.randn(5,4)

array([[-0.3011655 ,  1.5539327 ,  0.15957585, -1.42585359],
       [ 0.50792879,  2.24186417, -2.12877438, -0.99667391],
       [-0.42515062,  1.21034805, -0.77921845,  0.26624646],
       [ 0.5023458 ,  0.17394687,  0.13950935,  1.07806654],
       [-0.00305259,  1.55180302, -0.41599146,  1.6659961 ]])

In [25]:
np.random.randint(1,1000)

806

In [27]:
np.random.randint(1,50,20)

array([ 7, 34,  1,  2, 21,  2, 12, 33, 47, 25, 19, 45, 12,  9, 23, 46, 36,
       49, 44,  2])

In [30]:
arr.reshape(4,5)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
arr = np.arange(20)

#### Indexing and Slicing

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[8]

8

In [51]:
arr[3:9]

array([3, 4, 5, 6, 7, 8])

In [52]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

#### BroadCasting

In [53]:
arr[0:2] = 1001

In [54]:
arr

array([1001, 1001,    2,    3,    4,    5,    6,    7,    8,    9,   10])

In [55]:
arr_snip = arr[5:9]

In [57]:
arr_snip[:] = 201

In [58]:
arr_snip

array([201, 201, 201, 201])

#### Selection

In [72]:
two_array = np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))

In [73]:
two_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
two_array[2][2]

9

In [76]:
two_array[1][0]

4

In [77]:
two_array[:2,1:]

array([[2, 3],
       [5, 6]])

In [79]:
df = np.arange(1,11)

In [81]:
df > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [83]:
df1 = df > 6

In [87]:
var = df[df > 2]
var

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### More in builts function

In [91]:
two_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [92]:
two_array * two_array

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [93]:
two_array / two_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
two_array + two_array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [95]:
two_array.min()

1

In [96]:
two_array.max()

12

In [97]:
two_array.argmax()

11

In [98]:
two_array.argmin()

0