# Numpy Exercises

<b> Do note that if you are using random function, numbers may differ in various places.</b>
<b> Also , please be careful with execution as it may erase the solution given to corresponding exercises.</b>
#### Good Luck!

####  Import numpy as np

#### Question 1: Create a null array of size 10.  Hint Zero Array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Question 2: Create a null array of size 10 but the fifth value which is 1

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Question 3:Create a array with values ranging from 10 to 49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Question 4: Reverse a array (first element becomes last)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### Question 5: Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Question 6: Find indices of non-zero elements from [1,2,0,0,4,0]

(array([0, 1, 4]),)


#### Question 7: Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Question 8: Create a 3x3x3 array with random values

array([[[0.98293262, 0.41454015, 0.58932828],
        [0.59479278, 0.34841299, 0.07477092],
        [0.95502592, 0.71080533, 0.97962201]],

       [[0.23967446, 0.57185737, 0.19599282],
        [0.75075735, 0.11377249, 0.75438845],
        [0.27231156, 0.50022472, 0.4361032 ]],

       [[0.46282375, 0.14641322, 0.54835753],
        [0.46710933, 0.97287492, 0.28718568],
        [0.28622963, 0.98678761, 0.54297045]]])

#### Question 9: Create a 10x10 array with random values and find the minimum and maximum values

0.03447211871700817 0.9979815191724277


#### Question 10: Create a random vector of size 30 and find the mean value

0.592079156345253


#### Question 11:Create a 2d array with 1 on the border and 0 inside

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### Question 12: Normalize a 5x5 random matrix. Hint: formula is ( Z - Zmin)/ (Zmax - Zmin)

[[0.59626518 0.68649943 0.17019251 0.72150245 0.11622079]
 [0.91451558 0.76759636 0.14876523 0.02979399 0.19077935]
 [0.71030618 0.62271639 0.         0.03897802 0.64855449]
 [0.69200405 0.36142447 0.43032457 1.         0.39511289]
 [0.20279603 0.9059945  0.6893875  0.36197591 0.61520028]]


#### Question 13:Multiply a 5x3 matrix by a 3x2 matrix (real matrix product). Hint: Use np.dot( )

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### Question 14: Create a random array of size 10 and sort it

[0.12164726 0.26143722 0.41191349 0.59871098 0.62346816 0.69354568
 0.71923761 0.79398222 0.79531612 0.91952019]


#### Question 15: Consider two random array A and B, check if they are equal.  Hint use np.allclose( )

False


#### Question 16: Create random array of size 10 and replace the maximum value by 0

[0.81419511 0.55690234 0.06733361 0.70334971 0.06967024 0.09577527
 0.         0.70876239 0.26915315 0.12131744]


### Good Job!

For more numpy practice, please refer to this [link](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)